### ISSUE TITLE
Forgotten to push

### ISSUE THREAD

**Issue by davidsowerby** [davidsowerby/kaytee-agent#62]
Produces a consistent message, but it could be much more informative

**Comment by davidsowerby** [comment]
org.eclipse.jgit.errors.MissingObjectException: Missing unknown 463e6ca4d81f3fd120b3bbece34115830174d9ab
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:163)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:234)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:859)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
	at org.eclipse.jgit.api.CreateBranchCommand.call(CreateBranchCommand.java:153)
 [wrapped] org.eclipse.jgit.api.errors.JGitInternalException: Missing unknown 463e6ca4d81f3fd120b3bbece34115830174d9ab
	at org.eclipse.jgit.api.CreateBranchCommand.call(CreateBranchCommand.java:272)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:223)
	at uk.q3c.build.gitplus.local.DefaultGitLocal.checkoutCommit(DefaultGitLocal.kt:242)
 [wrapped] uk.q3c.build.gitplus.local.GitLocalException: Unable to checkout commit 463e6ca4d81f3fd120b3bbece34115830174d9ab
	at uk.q3c.build.gitplus.local.DefaultGitLocal.checkoutCommit(DefaultGitLocal.kt:245)
	at uk.q3c.kaytee.agent.prepare.DefaultGitClone.execute(DefaultGitClone.kt:37)
 [wrapped] uk.q3c.kaytee.agent.build.BuildPreparationException: Git clone or checkout operation failed
	at uk.q3c.kaytee.agent.prepare.DefaultGitClone.execute(DefaultGitClone.kt:47)
	at uk.q3c.kaytee.agent.prepare.DefaultPreparationStage.execute(DefaultPreparationStage.kt:37)
	at uk.q3c.kaytee.agent.build.DefaultBuild.execute(DefaultBuild.kt:306)
	at uk.q3c.kaytee.agent.queue.DefaultBuildRunner.run(DefaultBuildRunner.kt:31)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
