### ISSUE TITLE
Jackson date failure in FunctionalTest1

### ISSUE THREAD

**Issue by davidsowerby** [davidsowerby/kaytee-agent#9]
Even with binding `ObjectMapper` to `HalMapper` (which has Java 8 date support pre-loaded) ... can live with this for testing by just using HalResource , but is there a deeper issue here?

18:39:50.105 [ratpack-compute-4-9] ERROR r.e.i.DefaultDevelopmentErrorHandler - exception thrown for request to /
com.fasterxml.jackson.databind.JsonMappingException: Expected type float, integer, or string.
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 191] (through reference chain: uk.q3c.simplycd.agent.build.BuildRecord["preparationStartedAt"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270) ~[jackson-databind-2.9.0.pr1.jar:2.9.0.pr1]
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:1619) ~[jackson-databind-2.9.0.pr1.jar:2.9.0.pr1]
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:218) ~[jackson-datatype-jsr310-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.deserialize(InstantDeserializer.java:48) ~[jackson-datatype-jsr310-2.8.6.jar:2.8.6]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:519) ~[jackson-databind-2.9.0.pr1.jar:2.9.0.pr1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:515) ~[jackson-databind-2.9.0.pr1.jar:2.9.0.pr1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:436) ~[jackson-databind-2.9.0.pr1.jar:2.9.0.pr1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1272) ~[jackson-databind-2.9.0.pr1.jar:2.9.0.pr1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:313) ~[jackson-databind-2.9.0.pr1.jar:2.9.0.pr1]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:147) ~[jackson-databind-2.9.0.pr1.jar:2.9.0.pr1]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3862) ~[jackson-databind-2.9.0.pr1.jar:2.9.0.pr1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2985) ~[jackson-databind-2.9.0.pr1.jar:2.9.0.pr1]
	at ratpack.jackson.internal.JsonParser.parse(JsonParser.java:61) ~[ratpack-core-1.4.6.jar:na]

**Comment by davidsowerby** [comment]
Confirmed HalMapper is being used by the mock subscriber
